<a href="https://colab.research.google.com/github/JurijJusel/Image/blob/t6-dir-reader/apple_banana_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [88]:
import pandas as pd
import matplotlib.pyplot as plt

import cv2
import numpy as np

import csv
import os

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Create df, image path, name

In [80]:
apple_banana_train_path = '/content/drive/MyDrive/Colab Notebooks/dataset/train'

In [77]:
image_url = []
folder_name=[]
for file_path, folders, files in os.walk(apple_banana_train_path):
  for file in files:
      full_path = os.path.join(file_path, file)
      image_url.append(full_path)
      direct = file_path.split('/')[7:]
      folder_name.append('/'.join(direct))


In [ ]:
folder_name_df = pd.DataFrame(folder_name, columns=['name'])
img_path_df = pd.DataFrame(image_url,columns=['image_path'] )
df = pd.concat([folder_name_df, img_path_df], axis=1)
df.to_csv('/content/drive/MyDrive/Colab Notebooks/apple_banana.csv', index=False)

In [84]:
apple_banana_df = '/content/drive/MyDrive/Colab Notebooks/apple_banana.csv'

# Create df grey array

In [85]:
read_apple_banana_df = pd.read_csv(apple_banana_df)
read_apple_banana_df.info()
read_apple_banana_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        143 non-null    object
 1   image_path  143 non-null    object
dtypes: object(2)
memory usage: 2.4+ KB


name                                         image_path
0  apple  /content/drive/MyDrive/Colab Notebooks/dataset...
1  apple  /content/drive/MyDrive/Colab Notebooks/dataset...
2  apple  /content/drive/MyDrive/Colab Notebooks/dataset...
3  apple  /content/drive/MyDrive/Colab Notebooks/dataset...
4  apple  /content/drive/MyDrive/Colab Notebooks/dataset...

In [87]:
read_apple_banana_df['image_path']


0      /content/drive/MyDrive/Colab Notebooks/dataset...
1      /content/drive/MyDrive/Colab Notebooks/dataset...
2      /content/drive/MyDrive/Colab Notebooks/dataset...
3      /content/drive/MyDrive/Colab Notebooks/dataset...
4      /content/drive/MyDrive/Colab Notebooks/dataset...
                             ...                        
138    /content/drive/MyDrive/Colab Notebooks/dataset...
139    /content/drive/MyDrive/Colab Notebooks/dataset...
140    /content/drive/MyDrive/Colab Notebooks/dataset...
141    /content/drive/MyDrive/Colab Notebooks/dataset...
142    /content/drive/MyDrive/Colab Notebooks/dataset...
Name: image_path, Length: 143, dtype: object

In [ ]:
for line in range(len(read_apple_banana_df)):
    line_path=read_apple_banana_df['image_path']


In [ ]:
image_lst=[]
folder_name=[]
for line in line_path:
    # print(line)
    img_path = cv2.imread(line)
    direct = line.split('/')[7:8]
    folder_name.append('/'.join(direct))
    img = plt.imread(line)
    gray_img = cv2.cvtColor(img_path, cv2.COLOR_RGB2GRAY)
    img_resized = cv2.resize(gray_img, (122,122))
    img_array = np.array(img_resized)
    image_gray_lst=[item for sublist in img_array for item in sublist]
    image_lst.append(image_gray_lst)


In [ ]:
img_data_df = pd.DataFrame(image_lst)
name_df = pd.DataFrame(folder_name, columns=['image_name'])
apple_banana_df_grey = pd.concat([img_data_df, name_df], axis=1)
apple_banana_df_grey.to_csv('/content/drive/MyDrive/Colab Notebooks/apple_banana_grey_df.csv', index=False)
       

# Data preprocessing

In [90]:
apple_banana_grey_df = '/content/drive/MyDrive/Colab Notebooks/apple_banana_grey_df.csv'
read_df = pd.read_csv(apple_banana_grey_df)
read_df

0    1    2    3    4    5    6    7    8    9  ...  14875  14876  \
0     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
1     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
2   -122 -121 -123  126 -126 -120 -118 -117 -118 -121  ...    -18    -29   
3     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
4     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
138   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
139  -76  -68  -61  -42  -32  -43  -54  -53  -79  -82  ...   -102     -2   
140   -2   -2   -2   -2   -2   -2   -2   -2   -2   -2  ...     -2     -2   
141   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
142  -58  -56  -56  -56  -56  -56  -56  -56  -56  -56  ...    -57    -57   

     14877  14878  14879  14880  14881  14882  14883  image_name  
0       -1     -1     -1     -1     -1     -1     -1       apple  
1       -1     -1     -1     -1     -1     -1     -1       apple  
2      -37    -42    -43    -33    -51    -41    -44       apple  
3       -1     -1     -1     -1     -1     -1     -1       apple  
4       -1     -1     -1     -1     -1     -1     -1       apple  
..     ...    ...    ...    ...    ...    ...    ...         ...  
138     -1     -1     -1     -1     -1     -1     -1      banana  
139     -1     -1     -1     -1     -1     -1     -1      banana  
140     -2     -2     -2     -2     -2     -2     -2      banana  
141     -1     -1     -1     -1     -1     -1     -1      banana  
142    -57    -57    -57    -57    -57    -57    -60      banana  

[143 rows x 14885 columns]

In [91]:
read_df['image_name']

0       apple
1       apple
2       apple
3       apple
4       apple
        ...  
138    banana
139    banana
140    banana
141    banana
142    banana
Name: image_name, Length: 143, dtype: object

In [92]:
#making instance of labelencoder()
# Encode target labels ('image_name') with value
le = LabelEncoder()
encoded = le.fit_transform(read_df['image_name'])
encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [93]:
# removing the original column ''image_name'' from read_df
read_df.drop('image_name', axis=1, inplace=True)

In [94]:
# printing Dataframe without 'image_name' column
read_df

0    1    2    3    4    5    6    7    8    9  ...  14874  14875  \
0     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
1     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
2   -122 -121 -123  126 -126 -120 -118 -117 -118 -121  ...    -37    -18   
3     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
4     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
138   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
139  -76  -68  -61  -42  -32  -43  -54  -53  -79  -82  ...   -115   -102   
140   -2   -2   -2   -2   -2   -2   -2   -2   -2   -2  ...     -2     -2   
141   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
142  -58  -56  -56  -56  -56  -56  -56  -56  -56  -56  ...    -57    -57   

     14876  14877  14878  14879  14880  14881  14882  14883  
0       -1     -1     -1     -1     -1     -1     -1     -1  
1       -1     -1     -1     -1     -1     -1     -1     -1  
2      -29    -37    -42    -43    -33    -51    -41    -44  
3       -1     -1     -1     -1     -1     -1     -1     -1  
4       -1     -1     -1     -1     -1     -1     -1     -1  
..     ...    ...    ...    ...    ...    ...    ...    ...  
138     -1     -1     -1     -1     -1     -1     -1     -1  
139     -2     -1     -1     -1     -1     -1     -1     -1  
140     -2     -2     -2     -2     -2     -2     -2     -2  
141     -1     -1     -1     -1     -1     -1     -1     -1  
142    -57    -57    -57    -57    -57    -57    -57    -60  

[143 rows x 14884 columns]

In [95]:
encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
# Split arrays or matrices into random train and test subsets
X_train, X_test, y_train, y_test = train_test_split(read_df, encoded, test_size=0.33, random_state=42)

In [97]:
X_train

0   1   2   3   4   5   6   7   8   9  ...  14874  14875  14876  14877  \
25   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...     -1     -1     -1     -1   
23    8   8   8   9   9   9   9   9   9   9  ...   -113    123   -121   -115   
115  33  34  36  35  39  45  51  48  39  38  ...     77     77     75     75   
67   -6  -5  -6  -5  -4  -4  -6 -66  59 -45  ...     13     16     12     17   
44   35  35  35  35  35  35  35  35  35  35  ...    -69    -68    -69    -69   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...    ...    ...    ...    ...   
71   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...     -1     -1     -1     -1   
106   0   0   0   0   0   0   0   0   0   0  ...      0      0      0      0   
14   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...     -2     -1     -1     -1   
92   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...     -1     -1     -1     -1   
102  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...     -1     -1     -1     -1   

     14878  14879  14880  14881  14882  14883  
25      -1     -1     -1     -1     -1     -1  
23    -106   -112   -104   -107   -110   -115  
115     74     73     72     71     68     68  
67       6     45     50     40     24     16  
44     -68    -70    -70    -70    -70    -70  
..     ...    ...    ...    ...    ...    ...  
71      -1     -1     -1     -1     -1     -1  
106      0      0      0      0      0      0  
14      -1     -1     -1     -1     -1     -1  
92      -1     -1     -1     -1     -1     -1  
102     -1     -1     -1     -1     -1     -1  

[95 rows x 14884 columns]

In [98]:
X_test

0    1    2    3    4    5    6    7    8    9  ...  14874  14875  \
117  110  101   78   41  116   48   57   72   62   21  ...     70     76   
19   112  116  118  122  120 -126  126  124  126  120  ...     87     90   
82    50   49   45   33   26   33   30   27   34   38  ...    119   -119   
97    -4   -4   -4   -4   -4   -4   -4   -4   -4   -4  ...     -4     -4   
56    45   37   45  117  -76  -60 -122   72   45   40  ...     59     57   
12   -14  -13  -13  -13  -14  -13  -13  -13  -13  -12  ...    -10     -9   
131   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
65    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
66    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...   -101   -101   
18    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
51    93  114   94   93   91   93  108  100  124  108  ...     25     22   
78    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
94    72   61   69   77   70   86   75   72   71   85  ...     66     68   
132 -103 -103 -108 -105 -109  -72  -61  -85 -103 -106  ...     49     50   
100   -1   -1   -1   -1   -1   -1   -5   -1  -29   95  ...     -1     -1   
64    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
27    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
69     0    0    0    0    0    0    0    0    0    0  ...      0      0   
125  -85  -85  -85  -85  -85  -85  -85  -85  -85  -85  ...    -85    -85   
73     0    0    0    0    0    0    0    0    0    0  ...      0      0   
11     0    0    0    0    0    0  118  126 -128 -124  ...    126    116   
119    0    0    0    0    0    0    0    0    0    0  ...      0      0   
110   37   21   29   39   31   21   25   49   30   21  ...     16     28   
113   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
55     0    0    0    0    0    0    0    0    0    0  ...      0      0   
45   117  114  114  113  116  115  112  115  115  114  ...     57     59   
9    -12  -13  -13  -13  -14  -13  -12  -13  -11  -12  ...     -7     -8   
4     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
26    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
124   -1   -1   -1   -1   -1   -2   -1   -1   -2   -1  ...     -1     -1   
31    79   69 -127  116  103  105   59   77   63   71  ...    104     74   
98    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
36     0    0    0    0    0    0    0    0    0    0  ...      0      0   
16   -17  -17  -14  -17  -15  -17  -20  -19  -17  -19  ...     -4     -4   
10    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
93    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
111    0    0    0    0    0    0    0    0    0    0  ...      0      0   
42    72   73   72   76   73   77   81   78   76   74  ...     11     14   
118   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
127   44   38   33   33   35   34   34   34   34   34  ...     -2     -2   
96   -84  -84  -84  -84  -82  -83  -82  -82  -81  -81  ...    -79    -70   
60    43   33   33   32   31   29   33   33   61  111  ...     70     71   
0     -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
84    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
28   -94   66   59   58  111  125  107  127   91   81  ...     49     48   
40    -1   -1   -1   -1   -1   -1   -1   -1   -1   -1  ...     -1     -1   
86   -61  -64  -77  -84  -81  -80  -65  -56  -51  -50  ...    105    105   
24    33   15   13   19   58   52   11   10   10    7  ...     14     13   

     14876  14877  14878  14879  14880  14881  14882  14883  
117     72     77     73     71     72     67     77     74  
19      92     91     73     80     77     76     77     76  
82     -77    -68    -69     98    126     16    126     31  
97      -4     -4     -4     -4   

In [99]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1])

In [100]:
y_test

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0])